#!/usr/bin/env bash
# scripts/install-hooks.sh — one-time, per-clone install of local git hooks.
#
# Git hooks live in .git/hooks/, which is NOT versioned/cloned — every
# contributor (and every worktree) needs to run this once. Idempotent.
#
# Usage: ./scripts/install-hooks.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOKS_DIR="$(cd "$REPO_ROOT" && git rev-parse --git-path hooks)"

install_hook() {
  local name="$1" src="$2"
  local dest="$HOOKS_DIR/$name"
  local base; base="$(basename "$src")"
  # Install a SHIM that execs the repo script — never a copy of it. A copy is a
  # snapshot: every later edit to scripts/<hook>.sh silently fails to reach the
  # installed hook, nothing reports the divergence, and the stale copy keeps
  # answering with old logic. That is the same freshness trap as a plugin cache
  # or an include_str!'d constant, and it is avoidable here for two lines.
  # Resolved at run time so the hook is whatever the working tree currently says;
  # the install-time path is only a fallback for an exotic GIT_DIR.
  cat > "$dest" <<SHIM
#!/usr/bin/env bash
# Generated by scripts/install-hooks.sh — do NOT edit.
# This is a shim; the real hook is scripts/$base in the repo. Edit that.
root="\$(git rev-parse --show-toplevel 2>/dev/null || true)"
[ -n "\$root" ] || root="$REPO_ROOT"
exec "\$root/scripts/$base" "\$@"
SHIM
  chmod +x "$dest"
  echo "✓ installed $name -> $dest (shim -> scripts/$base)"
}

install_hook "pre-push" "$REPO_ROOT/scripts/pre-push-guard.sh"

echo ""
echo "Hooks installed. Uninstall: rm '$HOOKS_DIR/pre-push'"
echo "Override for an intentional force-push to main: ALLOW_FORCE_PUSH_MAIN=1 git push ..."
